### ISSUE TITLE
Ansible run fail on when use python 3 Ansible  

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [ernestas-poskus/ansible-prometheus#26]
//Added later
Hello! 

During provisioning my Vagrant box with prometheus i have issue as below

Ansible 2.3.2.0 fails during installation of systemd service:
`TASK [ernestas-poskus.ansible-prometheus : Install Prometheus systemd service] ***
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}`

The issue probably occurs because python 3 don't have attribute iteritems, on Ansible with python 2 role works as intended 

https://wiki.python.org/moin/Python3.0 (abotu changes between versions) 

Kind regards

**Comment by ernestas-poskus** [comment]
@tomaszkrzyzanowski please provide stacktrace/output

**Comment by tomaszkrzyzanowski** [comment]
I have added something

**Comment by ernestas-poskus** [comment]
Thank you, I will try to reproduce on testing environment with Python 3 and then will get back to you

**Comment by ernestas-poskus** [comment]
If the issue is resolved please close

**Comment by ernestas-poskus** [comment]
ping @tomaszkrzyzanowski

**Comment by tomaszkrzyzanowski** [comment]
Sorry for delay ;) 

Looks fine for me, i've started use this version (1.7.1) for internal purposes

Thanks for quick resolution ;) 
Regards
