### ISSUE TITLE
promtool syntax changes in prometheus version 2

### ISSUE THREAD

**Issue by itsuugo** [ernestas-poskus/ansible-prometheus#33]
I tried to use this playbook to install prometheus version 2, but it's failing because the right syntax in version 2 is `promtool check rules` instead of `promtool check-rules`. 
It happens the same for `promtool check config`.

**Comment by ernestas-poskus** [comment]
@itsuugo thanks for reporting this, I am almost finished with P2 support I will land PR today

**Comment by itsuugo** [comment]
Awesome,

I also noticed that the syntax rules check is failing, it seems that now they are using yaml for the rules

**Comment by ernestas-poskus** [comment]
Thanks @itsuugo for tips, you saved me some time :+1: I have released 3.0.0 version check if works for you and close it if everything is :ok_hand: .

**Comment by ernestas-poskus** [comment]
ping @itsuugo

**Comment by itsuugo** [comment]
Sorry for the delay, I can't check this now but I see that your tests are passing so I think that we can close the issue

https://travis-ci.org/ernestas-poskus/ansible-prometheus/jobs/303606058
