### ISSUE TITLE
REQ: snmp-exporter install option

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#43]
just like the push-gateway install, an option to install the snmp-exporter with basic mib walk.

**Comment by ernestas-poskus** [comment]
I see that it uses 'generated' configuration https://github.com/prometheus/snmp_exporter#configuration

**Comment by ernestas-poskus** [comment]
Furthermore looks like there is default snmp.yml config that does most of the job, I guess I will just include it.

**Comment by ernestas-poskus** [comment]
Added.

**Comment by madeinoz67** [comment]
man you're quick, I had forked it with teh intention of implementing over the break and you've beaten me to it 👍

**Comment by ernestas-poskus** [comment]
Sorry, wanted to make few complete and self contained examples :)

**Comment by madeinoz67** [comment]
no complaints here :D 

thanks again
