### ISSUE TITLE
REQ: blackbox-exporter install option

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#44]
option to install the blackbox-exporter

**Comment by ernestas-poskus** [comment]
https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md

I assume blackbox configuration constitutes of top YAML key `modules` and then everything else as its ancestors?

**Comment by ernestas-poskus** [comment]
Added.

**Comment by ernestas-poskus** [comment]
Let me know if `modules` is enough https://github.com/ernestas-poskus/ansible-prometheus/blob/master/templates/blackbox.yml.j2#L2 then I will make a new release else you can make PR if you want :)

**Comment by madeinoz67** [comment]
thanks I will have a play over the next couple of days and make any changes I think would be required and submit a PR

**Comment by ernestas-poskus** [comment]
hey @madeinoz67 what about a new release?

**Comment by madeinoz67** [comment]
Merry christmas @ernestas-poskus Sorry I haven't had time to play due to Christmas break, however I'm back at work tomorrow so will try out. 

If you want to release as is and if any changes I'll submit a PR?l

**Comment by ernestas-poskus** [comment]
Merry Christmas to you too, no rush, let me know
