### ISSUE TITLE
Node Exporter 1.16.0 introducing braking changes

### ISSUE THREAD

**Issue by Cosaquee** [ernestas-poskus/ansible-prometheus#66]
Latest release of node-exporter is introducing breaking changes in metrics name. I think that it would be nice to add some note to README when you will bump node_exporter version. That way if someone does not follow node-exporter repository at least will have chance to not be surprised when everything  stops working(alerts, dashboards).

Link to rc: https://github.com/prometheus/node_exporter/releases/tag/v0.16.0-rc.0

**Comment by ernestas-poskus** [comment]
Thank you for the issue, I usually mention breaking changes in releases https://github.com/ernestas-poskus/ansible-prometheus/releases. Do you think it is worth mentioning in README as well? In case of breaking changes for node exporter 0.16.0 when the 0.17.0 version will come out should 0.16.0 notes stay?

**Comment by Cosaquee** [comment]
I`m not sure how to do it but maybe section in README about upgrading between versions could be nice. It is also duplication of informations available in node-exporter or prometheus so you need to decide if you want to provide that info. 

The problem is that when you bump node-exporter version or some other exporter to version with breaking changes you are introducing breaking change for you library. Probably it would be nice to inform users about that in README also as not everyone is looking into releases.

Maybe providing some compatibility matrix would be nice but it might be unnecessary and hard to maintain.

For example with the latest Prometheus team wants to provide sample `metric_relabel_config` for backward compatibility(https://github.com/prometheus/node_exporter/issues/830).

**Comment by ernestas-poskus** [comment]
Related https://github.com/ernestas-poskus/ansible-prometheus/pull/73

No backward compatibility as it will complicate maintenance of playbook it up to the user to migrate to the new format of /metrics.

**Comment by ernestas-poskus** [comment]
bumped
