### ISSUE TITLE
Please bump installed component versions 

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#70]
Prometheus: 2.4.3
Alert Manager: 0.15.2

**Comment by madeinoz67** [comment]
looks like the new version of alert manager is now using cluster_listen_address rather than mesh_listen_address

**Comment by ernestas-poskus** [comment]
Done, I have pulled your changes from https://github.com/ernestas-poskus/ansible-prometheus/pull/71
thank you for your contribution :bowing_man: :+1:
