### ISSUE TITLE
Add support to remote write and read

### ISSUE THREAD

**Issue by gorkarevilla** [ernestas-poskus/ansible-prometheus#77]
It would be nice to be able to configure Prometheus to support remote and write: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read

This should fix it: https://github.com/ernestas-poskus/ansible-prometheus/pull/78

**Comment by ernestas-poskus** [comment]
Thank you for the contribution
