### ISSUE TITLE
running in check mode fails for blackbox exporter

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#83]
when a playbook is run in check mode its failing when trying to elevate permissions of the install directory.

It fails as it has not downloaded the relevant install file so directory does not yet exist 

therefore the task that sets the elevated directory permissions needs `when: not check_mode` needs to be added to task `name: Apply elevated privileges to blackbox_exporter for ICMP probe` in https://github.com/ernestas-poskus/ansible-prometheus/blob/master/tasks/install-blackbox_exporter.yml

**Comment by ernestas-poskus** [comment]
Hey @madeinoz67 

Thank you for reporting this, maybe you are willing to make a fix?

**Comment by madeinoz67** [comment]
yes that's my intention just have been under the pump since returning after the new year.  its only minor. I'll try and get to it in the next couple of days. happy for you to assign to me
