### ISSUE TITLE
Broken links to docs in README

### ISSUE THREAD

**Issue by talonx** [ernestas-poskus/ansible-prometheus#93]
E.g. "DOCS: Prometheus variables" in the README at https://galaxy.ansible.com/ernestas-poskus/ansible-prometheus points to a non-existent URL https://galaxy.ansible.com/docs/prometheus.md

**Comment by ernestas-poskus** [comment]
probably because they are relative, will fix, thanks

**Comment by ernestas-poskus** [comment]
Added absolute links in 4.13.0 release
